future: true
permalink: /:title/
url: http://zhongrliu.github.io
name: ZhongRongLiu
author: Zhong
qq: yourqq
email: zhongrliu@mail2.sysu.edu.cn

duoshuo: ZhongRongLiu
beian: 
cnzz: 
weibo: 
github: zhongrliu
about: "这里是 zhongzhongliu 的个人博客，创建于 2018 年。"

safe: true
paginate: 20
